config/routes.rb
Rails.application.routes.draw do
  root 'users#login'
  resources :users
  resources :messages
  resources :contacts
  post "login" => "users#signup"
  get "login" => "users#login"

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :message
  has_many :contact
  validates :email, uniqueness: true

  def self.bulk_insert
    alpha = ("a".."z").to_a
    1.upto(10000).each do |x|
      user=User.new
      user.email = "#{alpha.sample(4).join}_#{x}@gmail.com"
      user.name = alpha.sample(5).join
      user.password = user.name
      user.save
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def index
    @user  = User.find(session[:current_user_id])
    if @user.present?
      @contact = @user.contact
    else
      redirect_to '/login'
    end
  end

  def create
    contact = Contact.new(contact_params)
    @user  = User.find(session[:current_user_id])
    contact.user_id = @user.id
    if contact.save
      redirect_to '/contacts'
    else
      format.html { render :new }
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    contact = Contact.find(params[:id])
    if contact.update(contact_params)
      redirect_to '/contacts'
    else
      render 'edit'
    end
  end

  def destroy
    contact = Contact.find(params[:id])
    contact.destroy
    redirect_to contacts_path
  end

  private
  def contact_params
    params.require(:contact).permit(:name,:email,:phone,:address)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @user  = User.find(session[:current_user_id])
    if @user.present?
    @message = Message.where(:reciver_id => @user.id)
    @contact = @user.contact
    else
      redirect_to '/login'
    end
  end

  def new
    @user  = User.find(session[:current_user_id])
    @message = Message.new
    @message.sendername = @user.name
  end

  def create
    existuser = User.find(session[:current_user_id])
    @user  = User.find_by_name(message_params[:toname])
    if @user.present?
    @message = Message.new(message_params)
    @message.user_id = existuser.id
    @message.reciver_id=@user.id
      if @message.save
        redirect_to '/messages'
      else
          format.html { render :new }
      end
    else
      format.html { render :new }
    end
  end

  private
  def message_params
    params.require(:message).permit(:toname,:sendername,:msg)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    userexist = User.find_by_email(@user.email)
    User.bulk_insert
    if userexist.present?
      redirect_to '/login' , notice: 'User already present'
    else
      if @user.save
        respond_to do |format|
          format.html { redirect_to '/login', notice: 'User was successfully created.' }
        end
      else
        #format.html { render :new }
        render :new
      end
    end
  end

  def login
    @user = User.new
  end

  def signup
    @user  = User.find_by_email(user_params[:email])
    if @user.present? && @user.password ==(user_params[:password])
      session[:current_user_id] = @user.id
      redirect_to '/messages'
    else
      redirect_to '/login'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name,:password,:email,:contactno,:about,:address,:age)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= form_for (@contact) do |f| %>
<table>
<tr>
  <td>
   <%= f.label :name %>
  </td>
  <td>
   <%= f.text_field :name %>
  </td>
</tr>
<tr>
  <td>
   <%= f.label :email %>
  </td>
  <td>
    <%= f.text_field :email %>
  </td>
</tr>
<tr>
  <td>
   <%= f.label :phone %>
  </td>
  <td>
   <%= f.text_field :phone %>
  </td>
</tr>
<tr>
  <td>
    <%= f.label :address %>
  </td>
  <td>
   <%= f.text_field :address %>
  </td>
</tr>
</table>
<div class="actions" style="text-align: center;position: fixed;top: 33%;left: 7%;">
  <%= f.submit %>
</div>

<% end %>

app/views/contacts/edit.html.erb
<h1>Edit contacts</h1>

<%= render 'form' %>

<div style="text-align: center;position: fixed;top: 37%;left: 9%;">
   or
  <br>
<%= link_to 'Contacts', contacts_path %>
</div>

app/views/contacts/index.html.erb
<table align="center">
<tr>
<td>
<table class="tabelcs">
  <h1> Contacts  </h1>
  <tr>
    <th>Contact Name</th>
    <th>phone</th>
    <th>email</th>
    <th>address</th>
    <th></th>
    <th></th>
  </tr>
<% @contact &&  @contact.each do |f| %>
          <tr>
            <td><%=f.name%></td>
            <td><%=f.phone%></td>
	    <td><%=f.email%></td>
            <td><%=f.address%></td>
	      <td><%= link_to 'Edit', edit_contact_path(f) %></td>
              <td><%= link_to 'Destroy', contact_path(f),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
          </tr>
  <% end %>
       </table>
</td>
</tr>
</table>
<div style="text-align: center;position: fixed;top: 9%;left: 5%;">
<%= link_to 'New Contact', new_contact_path %>
</div>
<div style="text-align: center;position: fixed;top: 12%;left: 5%;">
<%= link_to 'Home', messages_path %>
</div>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<div style="text-align: center;position: fixed;top: 37%;left: 9%;">
   or
  <br>
<%= link_to 'Contacts', contacts_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= session[:current_user_id].present? ? (link_to 'logout', login_path) : "login" %>
<%= flash[:notice]%>
<%= yield %>
</body>
</html>

app/views/messages/index.html.erb
<table align="center">
  <tr>
  <td>
 <table class="tabelcs">
   <h1> Messages </h1>
  <tr>
    <th>Sender Name</th>
    <th>Message</th>
  </tr>
<% @message &&  @message.each do |f| %>
          <tr>
            <td><%=f.sendername%></td>
            <td><%=f.msg%></td>
          </tr>
  <% end %>
       </table>
  </td>
  <td>
    &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
  </td>
  <td>
    <table class="tabelcs">
      <h1> Contacts </h1>
    <tr>
    <th>Name</th>
    <th>Phone</th>
     <th>E-mail</th>
    <th>Addess</th>
    <th></th>
    <th></th>
  </tr>
<% @contact &&  @contact.each do |g| %>
          <tr>
           <td><%=g.name%></td>
            <td><%=g.phone%></td>
	    <td><%=g.email%></td>
            <td><%=g.address%></td>
	      <td><%= link_to 'Edit', edit_contact_path(g) %></td>
              <td><%= link_to 'Destroy', contact_path(g),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
          </tr>
  <% end %>
     </table>
  </td>
  </tr>
  </table>

<div style="text-align: center;position: fixed;top: 9%;left: 5%;">
<%= link_to 'New Message', new_message_path %>
<div>

<div style="text-align: center;position: fixed;top: 12%;left: 5%;">
<%= link_to 'View contacts', contacts_path %>
<div>

app/views/messages/new.html.erb
<h1>New Message</h1>

<div>
<%= form_for (@message) do |f| %>
<table>
  <tr>
    <td>
    <%= f.label :sendername %>
    </td>
    <td>
      <%= f.text_field :sendername ,:readonly => true%>
    </td>
  </tr>
  <tr>
    <td>
    <%= f.label :toname %>
    </td>
    <td>
    <%= f.text_field  :toname %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.label :msg %>
    </td>
    <td>
      <%= f.text_field :msg %>
    </td>
  </tr>
 </table>
<div class="action"class="actions" style="text-align: center;position: fixed;top: 30%;left: 9%;">
  <%= f.submit "Send Message"%>
</div>

<% end %>

<div style="text-align: center;position: fixed;top: 33%;left: 11%;">
   or
  <br>
<%= link_to 'Home', messages_path %>
</div>
</div>

app/views/users/login.html.erb
<div class="mydiv">
  <div style="text-align: center;position: fixed;left: 46%;">
  <h1>log in</h1>
  </div>
  <div style="text-align: center;position: fixed;top: 44%;left :40%">
  <%= form_for(@user, url: login_path) do |f| %>
  <table>
    <tr>
      <td>
	 <%= f.label :email %>
      </td>
      <td>
	 <%= f.text_field :email %>
      </td>
    </tr>
      <tr>
      <td>
	<%= f.label :password %>
      </td>
      <td>
	<%= f.password_field :password %>
      </td>
    </tr>
  </table>
  <div>
<div class="actions" style="text-align: center;position: fixed;top: 54%;left: 49%;">
  <%= f.submit "Login" %>
</div>
<% end %>
<div style="text-align: center;position: fixed;top: 67%;left: 45%;">
Not a user &nbsp; <%= link_to 'sign up', new_user_path %>
</div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<div>
<%= form_for (@user) do |f| %>

<table>
  <tr>
    <td>
      <%= f.label :name %>
    </td>
    <td>
      <%= f.text_field :name %>
    </td>
    </tr>
   <tr>
    <td>
       <%= f.label :email %>
    </td>
    <td>
        <%= f.text_field :email %>
    </td>
    </tr>
    <tr>
    <td>
       <%= f.label :password %>
    </td>
    <td>
        <%= f.password_field :password %>
    </td>
    </tr>
     <tr>
    <td>
       <%= f.label :contactno %>
    </td>
    <td>
       <%= f.text_field :contactno %>
    </td>
    </tr>
     <tr>
    <td>
     <%= f.label :age %>
    </td>
    <td>
     <%= f.text_field :age %>
    </td>
    </tr>
      <tr>
    <td>
     <%= f.label :about %>
    </td>
    <td>
     <%= f.text_field :about %>
    </td>
    </tr>
    <tr>
    <td>
     <%= f.label :address %>
    </td>
    <td>
    <%= f.text_field :address %>
    </td>
    </tr>
  </table>

<div class="actions" style="text-align: center;position: fixed;top: 45%;left: 9%;">
  <%= f.submit %>
</div>

<% end %>

<div style="text-align: center;position: fixed;top: 48%;left: 11%;">
   or
  <br>
<%= link_to 'login', login_path %>
<div >
</div>